export const CITY_OPTIONS = [
  { id: 0, name: '臺北市 / 新北市', en: 'Taipei / NewTaipei', value: 'Taipei', color: 'text-blue-dark', fill: '#283C43' },
  { id: 1, name: '桃園市', en: 'Taoyuan', value: 'Taoyuan', color: 'text-blue', fill: '#3591C5' },
  { id: 2, name: '臺中市', en: 'Taichung', value: 'Taichung', color: 'text-secondary', fill: '#D08181' },
  { id: 3, name: '臺南市', en: 'Tainan', value: 'Tainan', color: 'text-green', fill: '#7FC0C5' },
  { id: 4, name: '高雄市', en: 'Kaohsiung', value: 'Kaohsiung', color: 'text-teal', fill: '#5E9BAE' },
  { id: 5, name: '其他地區', en: 'Other City', value: '', color: 'text-green-dark', fill: '#52797C' },
] as const;

export const CITY_SELECT_OPTIONS = [
  { value: 'Keelung', label: '基隆市' },
  { value: 'Taipei', label: '臺北市' },
  { value: 'NewTaipei', label: '新北市' },
  { value: 'YilanCounty', label: '宜蘭縣' },
  { value: 'Taoyuan', label: '桃園市' },
  { value: 'Hsinchu', label: '新竹市' },
  { value: 'HsinchuCounty', label: '新竹縣' },
  { value: 'HualienCounty', label: '花蓮縣' },
  { value: 'TaitungCounty', label: '臺東縣' },
  { value: 'MiaoliCounty', label: '苗栗縣' },
  { value: 'Taichung', label: '臺中市' },
  { value: 'ChanghuaCounty', label: '彰化縣' },
  { value: 'NantouCounty', label: '南投縣' },
  { value: 'YunlinCounty', label: '雲林縣' },
  { value: 'Chiayi', label: '嘉義市' },
  { value: 'ChiayiCounty', label: '嘉義縣' },
  { value: 'Tainan', label: '臺南市' },
  { value: 'Kaohsiung', label: '高雄市' },
  { value: 'PingtungCounty', label: '屏東縣' },
  { value: 'PenghuCounty', label: '澎湖縣' },
  { value: 'KinmenCounty', label: '金門縣' },
  { value: 'LianjiangCounty', label: '連江縣' },
] as const;

export const CITY_ABRIDGE_MAP = {
  Keelung: '基隆',
  Taipei: '臺北',
  NewTaipei: '新北',
  YilanCounty: '宜蘭',
  Taoyuan: '桃園',
  Hsinchu: '新竹',
  HsinchuCounty: '新竹',
  HualienCounty: '花蓮',
  TaitungCounty: '臺東',
  MiaoliCounty: '苗栗',
  Taichung: '臺中',
  ChanghuaCounty: '彰化',
  NantouCounty: '南投',
  YunlinCounty: '雲林',
  Chiayi: '嘉義',
  ChiayiCounty: '嘉義',
  Tainan: '臺南',
  Kaohsiung: '高雄',
  PingtungCounty:'屏東',
  PenghuCounty: '澎湖',
  KinmenCounty:'金門',
  LianjiangCounty:'連江',
} as const;

export const CITY_CODE_MAP = {
  KEE: 'Keelung',
  TPE: 'Taipei',
  NWT: 'NewTaipei',
  ILA: 'YilanCounty',
  TAO: 'Taoyuan',
  HSZ: 'Hsinchu',
  HSQ: 'HsinchuCounty',
  HUA: 'HualienCounty',
  TTT: 'TaitungCounty',
  MIA: 'MiaoliCounty',
  TXG: 'Taichung',
  CHA: 'ChanghuaCounty',
  NAN: 'NantouCounty',
  YUN: 'YunlinCounty',
  CYI: 'Chiayi',
  CYQ: 'ChiayiCounty',
  TNN: 'Tainan',
  KHH: 'Kaohsiung',
  PIF:'PingtungCounty',
  PEN: 'PenghuCounty',
  KIN:'KinmenCounty',
  LIE:'LianjiangCounty',
} as const;

export const CITY_KEYS = [
  'Keelung',
  'Taipei',
  'NewTaipei',
  'YilanCounty',
  'Taoyuan',
  'Hsinchu',
  'HsinchuCounty',
  'HualienCounty',
  'TaitungCounty',
  'MiaoliCounty',
  'Taichung',
  'ChanghuaCounty',
  'NantouCounty',
  'YunlinCounty',
  'Chiayi',
  'ChiayiCounty',
  'Tainan',
  'Kaohsiung',
  'PingtungCounty',
  'PenghuCounty',
  'KinmenCounty',
  'LianjiangCounty',
] as const;
