export const CITY_OPTIONS = [
  { id: 0, name: '臺北市 / 新北市', en: 'Taipei / NewTaipei', value: 'Taipei', color: 'text-blue-dark', fill: '#283C43' },
  { id: 1, name: '桃園市', en: 'Taoyuan', value: 'Taoyuan', color: 'text-blue', fill: '#3591C5' },
  { id: 2, name: '臺中市', en: 'Taichung', value: 'Taichung', color: 'text-secondary', fill: '#D08181' },
  { id: 3, name: '臺南市', en: 'Tainan', value: 'Tainan', color: 'text-green', fill: '#7FC0C5' },
  { id: 4, name: '高雄市', en: 'Kaohsiung', value: 'Kaohsiung', color: 'text-teal', fill: '#5E9BAE' },
  { id: 5, name: '其他地區', en: 'Other City', value: '', color: 'text-green-dark', fill: '#52797C' },
] as const;

export const CITY_SELECT_OPTIONS = [
  { value: 'Keelung', label: 'city.Keelung' },
  { value: 'Taipei', label: 'city.Taipei' },
  { value: 'NewTaipei', label: 'city.NewTaipei' },
  { value: 'YilanCounty', label: 'city.YilanCounty' },
  { value: 'Taoyuan', label: 'city.Taoyuan' },
  { value: 'Hsinchu', label: 'city.Hsinchu' },
  { value: 'HsinchuCounty', label: 'city.HsinchuCounty' },
  { value: 'HualienCounty', label: 'city.HualienCounty' },
  { value: 'TaitungCounty', label: 'city.TaitungCounty' },
  { value: 'MiaoliCounty', label: 'city.MiaoliCounty' },
  { value: 'Taichung', label: 'city.Taichung' },
  { value: 'ChanghuaCounty', label: 'city.ChanghuaCounty' },
  { value: 'NantouCounty', label: 'city.NantouCounty' },
  { value: 'YunlinCounty', label: 'city.YunlinCounty' },
  { value: 'Chiayi', label: 'city.Chiayi' },
  { value: 'ChiayiCounty', label: 'city.ChiayiCounty' },
  { value: 'Tainan', label: 'city.Tainan' },
  { value: 'Kaohsiung', label: 'city.Kaohsiung' },
  { value: 'PingtungCounty', label: 'city.PingtungCounty' },
  { value: 'PenghuCounty', label: 'city.PenghuCounty' },
  { value: 'KinmenCounty', label: 'city.KinmenCounty' },
  { value: 'LianjiangCounty', label: 'city.LianjiangCounty' },
] as const;

export const CITY_CODE_MAP = {
  KEE: 'Keelung',
  TPE: 'Taipei',
  NWT: 'NewTaipei',
  ILA: 'YilanCounty',
  TAO: 'Taoyuan',
  HSZ: 'Hsinchu',
  HSQ: 'HsinchuCounty',
  HUA: 'HualienCounty',
  TTT: 'TaitungCounty',
  MIA: 'MiaoliCounty',
  TXG: 'Taichung',
  CHA: 'ChanghuaCounty',
  NAN: 'NantouCounty',
  YUN: 'YunlinCounty',
  CYI: 'Chiayi',
  CYQ: 'ChiayiCounty',
  TNN: 'Tainan',
  KHH: 'Kaohsiung',
  PIF:'PingtungCounty',
  PEN: 'PenghuCounty',
  KIN:'KinmenCounty',
  LIE:'LianjiangCounty',
} as const;

export const CITY_KEYS = [
  'Keelung',
  'Taipei',
  'NewTaipei',
  'YilanCounty',
  'Taoyuan',
  'Hsinchu',
  'HsinchuCounty',
  'HualienCounty',
  'TaitungCounty',
  'MiaoliCounty',
  'Taichung',
  'ChanghuaCounty',
  'NantouCounty',
  'YunlinCounty',
  'Chiayi',
  'ChiayiCounty',
  'Tainan',
  'Kaohsiung',
  'PingtungCounty',
  'PenghuCounty',
  'KinmenCounty',
  'LianjiangCounty',
] as const;
