export const TAIPEI_KEYBOARD = [
  { value: 'red', color: 'text-white', bg: 'bg-red' },
  { value: 'blue', color: 'text-white', bg: 'bg-blue' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'green', color: 'text-white', bg: 'bg-green-light' },
  { value: 'brown', color: 'text-white', bg: 'bg-brown' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'orange', color: 'text-white', bg: 'bg-orange' },
  { value: 'yellow', color: 'text-white', bg: 'bg-yellow' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'F', color: 'text-white', bg: 'bg-gray-600' },
  { value: 'small', color: 'text-white', bg: 'bg-gray-600' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const TAOYUAN_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'L', color: 'text-white', bg: 'bg-blue-dark' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;


export const TAICHUNG_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'dedicated_lane', color: 'text-white', bg: 'bg-blue-dark' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const TAINAN_KEYBOARD = [
  { value: 'red', color: 'text-white', bg: 'bg-red' },
  { value: 'blue', color: 'text-white', bg: 'bg-blue' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'green', color: 'text-white', bg: 'bg-green-light' },
  { value: 'brown', color: 'text-white', bg: 'bg-brown' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'orange', color: 'text-white', bg: 'bg-orange' },
  { value: 'yellow', color: 'text-white', bg: 'bg-yellow' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'high_speed_rail', color: 'text-white', bg: 'bg-blue-dark col-span-2' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const KAOHSIUNG_KEYBOARD = [
  { value: 'red', color: 'text-white', bg: 'bg-red' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'orange', color: 'text-white', bg: 'bg-orange' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'metro', color: 'text-white', bg: 'bg-gray-600' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'express_line', color: 'text-white', bg: 'bg-gray-600' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const COMMON_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: 'clear', color: 'text-black', bg: 'bg-gray-500' },
] as const;
