export const TAIPEI_KEYBOARD = [
  { value: '紅', color: 'text-white', bg: 'bg-red' },
  { value: '藍', color: 'text-white', bg: 'bg-blue' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: '綠', color: 'text-white', bg: 'bg-green-light' },
  { value: '棕', color: 'text-white', bg: 'bg-brown' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: '橘', color: 'text-white', bg: 'bg-orange' },
  { value: '黃', color: 'text-white', bg: 'bg-yellow' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'F', color: 'text-white', bg: 'bg-gray-600' },
  { value: '小', color: 'text-white', bg: 'bg-gray-600' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const TAOYUAN_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 'L', color: 'text-white', bg: 'bg-blue-dark' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;


export const TAICHUNG_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: '專用道', color: 'text-white', bg: 'bg-blue-dark' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const TAINAN_KEYBOARD = [
  { value: '紅', color: 'text-white', bg: 'bg-red' },
  { value: '藍', color: 'text-white', bg: 'bg-blue' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: '綠', color: 'text-white', bg: 'bg-green-light' },
  { value: '棕', color: 'text-white', bg: 'bg-brown' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: '橘', color: 'text-white', bg: 'bg-orange' },
  { value: '黃', color: 'text-white', bg: 'bg-yellow' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: '高鐵', color: 'text-white', bg: 'bg-blue-dark col-span-2' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const KAOHSIUNG_KEYBOARD = [
  { value: '紅', color: 'text-white', bg: 'bg-red' },
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: '橘', color: 'text-white', bg: 'bg-orange' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: '幹線', color: 'text-white', bg: 'bg-gray-600' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: '快線', color: 'text-white', bg: 'bg-gray-600' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;

export const COMMON_KEYBOARD = [
  { value: 1, color: 'text-black', bg: 'bg-gray-500' },
  { value: 2, color: 'text-black', bg: 'bg-gray-500' },
  { value: 3, color: 'text-black', bg: 'bg-gray-500' },
  { value: 4, color: 'text-black', bg: 'bg-gray-500' },
  { value: 5, color: 'text-black', bg: 'bg-gray-500' },
  { value: 6, color: 'text-black', bg: 'bg-gray-500' },
  { value: 7, color: 'text-black', bg: 'bg-gray-500' },
  { value: 8, color: 'text-black', bg: 'bg-gray-500' },
  { value: 9, color: 'text-black', bg: 'bg-gray-500' },
  { value: 0, color: 'text-black', bg: 'bg-gray-500 col-span-2' },
  { value: '清除', color: 'text-black', bg: 'bg-gray-500' },
] as const;
